### PR TITLE
Update utils.test.js

### PR DESCRIPTION
**Pull request by bayernmunich**

### CODE REVIEW

**Comment by PhanindraReddyP** [comment]
Tests are Failing

**Review by NagarajCAPL — COMMENTED** [review]
test failed. So not merging to master

**Comment by PhanindraReddyP** [comment]
Tests are Passed

**Review by PhanindraReddyP — APPROVED** [review]
Tests are Passed

**Review by NagarajCAPL — APPROVED** [review]
All Good

**Pull request merged**
